version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "athena-blog"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jtlt9shsnyp2"
s3_prefix = "athena-blog"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ResourcePrefix=\"myapp\" S3BucketName=\"sensor-athena-blog\" CuratedKeyPrefix=\"/curated\" AthenaResultLocation=\"s3://sensor-athena-blog/athena_results\" DatabaseName=\"mydatabase\" SourceTableName=\"SourceTable\" TargetTableName=\"TargetTable\""
