version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jtlt9shsnyp2"
s3_prefix = "sam-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "S3BucketName=\"sensor-athena-blog\" CuratedKeyPrefix=\"/curated\" AthenaResultLocation=\"s3://sensor-athena-blog/athena_results\" DatabaseName=\"mydatabase\" SourceTableName=\"SourceTable\" TargetTableName=\"TargetTable\" BucketingKey=\"sensorID\" BucketCount=\"3\""
